### ISSUE TITLE
Parse git 

### ISSUE THREAD

**Issue by codingtwinky** [rtfpessoa/diff2html-nodejs#9]
Below is the git diff input and the result of the input.

I think there are some unicode parsing issues as result has doesn't quite handle `<`, `>` or other characters quite well.

```
diff --git a/components/textdiff/textdiff.html b/components/textdiff/textdiff.html
index a3484bf..82209af 100644
--- a/components/textdiff/textdiff.html
+++ b/components/textdiff/textdiff.html
@@ -1,6 +1,8 @@
 <!-- ko if: isShowingDiffs -->
 <div>
-  <div data-bind="event: { load: setDom($element) }"></div>
+  <!-- ko if: isParsed -->
+  <div data-bind="template: {nodes: ko.utils.parseHtmlFragment(htmlSrc())}"></div>
+  <!-- /ko -->
   <div class="btn-load-more" data-bind="visible: loadMoreCount() > 0">
     <span class="btn btn-warning" data-bind="click: loadMore, text: 'Load ' + loadMoreCount() + ' more lines'"></span>
   </div>
```

![screen shot 2015-06-21 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/5281068/8273266/6c55b60a-181a-11e5-883a-04304549daa4.png)

**Comment by rtfpessoa** [comment]
@codingtwinky this should be fixed on #10 .
If you are using highlightjs check the sample index.html on https://github.com/rtfpessoa/diff2html/blob/master/sample/index.html, since I changed the name of the line tags to avoid problems with the `-` and `+` prefixes.
